add_library(Toy3dAssetImport STATIC)
target_sources(Toy3dAssetImport PRIVATE "static_mesh_import.h" "static_mesh_import.cpp" "static_mesh_import_data.h")
target_compile_features(Toy3dAssetImport PUBLIC cxx_std_17)
set_target_properties(Toy3dAssetImport PROPERTIES CXX_EXTENSIONS OFF FOLDER "Engine/Tools")
target_include_directories(Toy3dAssetImport PUBLIC "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/..>")
target_link_libraries(Toy3dAssetImport PUBLIC Toy3dMeshBuilder PRIVATE assimp::assimp Toy3dAssetThumbnail)
target_compile_definitions(Toy3dAssetImport PUBLIC WITH_EDITORONLY_DATA=1)
